"""Add User and related models

Revision ID: 15e2eb38c036
Revises:
Create Date: 2026-04-09 14:24:02.880901

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15e2eb38c036"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("resort_name", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=255), nullable=False),
        sa.Column("location_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("location_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_parks_id"), "parks", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "attractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("park_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("area", sa.String(length=255), nullable=True),
        sa.Column("min_height_cm", sa.Integer(), nullable=True),
        sa.Column("avg_duration_min", sa.Integer(), nullable=True),
        sa.Column("thrill_level", sa.String(length=50), nullable=True),
        sa.Column("kid_friendly", sa.Boolean(), nullable=True),
        sa.Column("location_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("location_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("attraction_metadata", sa.JSON(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("park_id", "external_id", name="uix_park_attraction"),
    )
    op.create_index(op.f("ix_attractions_id"), "attractions", ["id"], unique=False)
    op.create_index(
        op.f("ix_attractions_park_id"), "attractions", ["park_id"], unique=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"),
        "password_reset_tokens",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(op.f("ix_sessions_token"), "sessions", ["token"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("has_kids", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("default_party_size", sa.Integer(), nullable=False),
        sa.Column("has_kids", sa.Boolean(), nullable=False),
        sa.Column("thrill_level", sa.String(length=50), nullable=False),
        sa.Column(
            "accessibility_needs",
            postgresql.ARRAY(sa.String(length=80)),
            nullable=False,
        ),
        sa.Column(
            "dietary_restrictions",
            postgresql.ARRAY(sa.String(length=80)),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_preferences_id"), "user_preferences", ["id"], unique=False
    )
    op.create_table(
        "itineraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("day_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("must_dos", postgresql.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("skip_list", postgresql.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "day_date", name="uix_trip_day"),
    )
    op.create_index(op.f("ix_itineraries_id"), "itineraries", ["id"], unique=False)
    op.create_index(
        op.f("ix_itineraries_trip_id"), "itineraries", ["trip_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_itinerary_id"),
        "chat_messages",
        ["itinerary_id"],
        unique=False,
    )
    op.create_table(
        "itinerary_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("attraction_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attraction_id"],
            ["attractions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("itinerary_id", "position", name="uix_itinerary_position"),
    )
    op.create_index(
        op.f("ix_itinerary_items_attraction_id"),
        "itinerary_items",
        ["attraction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_items_id"), "itinerary_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_items_itinerary_id"),
        "itinerary_items",
        ["itinerary_id"],
        unique=False,
    )
    op.create_table(
        "itinerary_parks",
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("park_id", sa.Integer(), nullable=False),
        sa.Column("visit_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.PrimaryKeyConstraint("itinerary_id", "park_id", name="pk_itinerary_park"),
    )
    op.create_index(
        op.f("ix_itinerary_parks_itinerary_id"),
        "itinerary_parks",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_parks_park_id"), "itinerary_parks", ["park_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_itinerary_parks_park_id"), table_name="itinerary_parks")
    op.drop_index(op.f("ix_itinerary_parks_itinerary_id"), table_name="itinerary_parks")
    op.drop_table("itinerary_parks")
    op.drop_index(op.f("ix_itinerary_items_itinerary_id"), table_name="itinerary_items")
    op.drop_index(op.f("ix_itinerary_items_id"), table_name="itinerary_items")
    op.drop_index(
        op.f("ix_itinerary_items_attraction_id"), table_name="itinerary_items"
    )
    op.drop_table("itinerary_items")
    op.drop_index(op.f("ix_chat_messages_itinerary_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_itineraries_trip_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_id"), table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index(op.f("ix_user_preferences_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_attractions_park_id"), table_name="attractions")
    op.drop_index(op.f("ix_attractions_id"), table_name="attractions")
    op.drop_table("attractions")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_parks_id"), table_name="parks")
    op.drop_table("parks")
    # ### end Alembic commands ###
