"""Make park slug not unique

Revision ID: 2acbadb46848
Revises: e71b8dba6c17
Create Date: 2026-04-16 08:42:11.275355

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2acbadb46848"
down_revision: Union[str, None] = "e71b8dba6c17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("parks_slug_key", "parks", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("parks_slug_key", "parks", ["slug"])
    # ### end Alembic commands ###
