"""add deleted column to trips table

Revision ID: e3b20201b7ec
Revises: f223de25cc85
Create Date: 2026-06-03 23:32:26.788645

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3b20201b7ec"
down_revision: Union[str, None] = "f223de25cc85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable with default value
    op.add_column(
        "trips", sa.Column("deleted", sa.Boolean(), nullable=True, default=False)
    )
    # Update all existing records to have deleted=False
    op.execute("UPDATE trips SET deleted = FALSE WHERE deleted IS NULL")
    # Now make the column NOT NULL
    op.alter_column("trips", "deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "deleted")
    # ### end Alembic commands ###
