"""Update user to require first_name

Revision ID: e71b8dba6c17
Revises: 0c25e869aa40
Create Date: 2026-04-14 19:29:21.859419

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e71b8dba6c17"
down_revision: Union[str, None] = "0c25e869aa40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=80), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=80), nullable=True
    )
    # ### end Alembic commands ###
