import { render, screen } from '@testing-library/react';
import RootLayout, { metadata } from '@/app/layout';

describe('RootLayout', () => {
  it('renders children correctly', () => {
    render(
      <RootLayout>
        <div data-testid="test-child">Test Content</div>
      </RootLayout>
    );

    expect(screen.getByTestId('test-child')).toBeInTheDocument();
    expect(screen.getByTestId('test-child')).toHaveTextContent('Test Content');
  });

  it('has correct metadata structure', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    });
  });

  it('renders multiple children correctly', () => {
    render(
      <RootLayout>
        <header data-testid="header">Header</header>
        <main data-testid="main">Main Content</main>
        <footer data-testid="footer">Footer</footer>
      </RootLayout>
    );

    expect(screen.getByTestId('header')).toBeInTheDocument();
    expect(screen.getByTestId('main')).toBeInTheDocument();
    expect(screen.getByTestId('footer')).toBeInTheDocument();
  });

  it('renders empty children without errors', () => {
    expect(() => render(<RootLayout>{null}</RootLayout>)).not.toThrow();
  });

  it('component renders without throwing errors', () => {
    // Test that the layout component can be rendered without errors
    expect(() => {
      render(
        <RootLayout>
          <div>Test content</div>
        </RootLayout>
      );
    }).not.toThrow();
  });
});
